# Generated by Django 6.1.1 on 2026-09-29 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('cpf_aluno', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=15)),
                ('curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('cpf_func', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='myapp.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atendimento', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendimento', to='myapp.agendamento')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='myapp.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Pendencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=30)),
                ('data_criacao', models.DateField()),
                ('atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendencias', to='myapp.atendimento')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='programas',
            field=models.ManyToManyField(to='myapp.programa'),
        ),
    ]
